name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  shared_preferences: ^2.0.15
  horizontal_week_calendar: ^0.0.20
  camera: ^0.11.0+2
  speech_to_text: ^7.3.0
  http: ^1.5.0
  image: ^4.1.3
  json_annotation: ^4.8.1
  flutter_sound: ^9.3.12
  web_socket_channel: ^3.0.3
  audioplayers: ^6.5.1
  uuid: ^4.3.3
  path_provider: ^2.1.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - images/cosmos.jpeg
    - images/northern_lights.png
    - images/northern_lights1.jpeg
    - images/northern_lights_bg.jpg
    - images/bg.jpg